name: Demo pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
  # schedule:
  #   - cron: "*/1 * * * *"     # Runs every minute

jobs:

  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create file
        run: |
           touch github-action.txt
           ls -la
           cat README.md file
           echo Hello World

    
  build_job:
    needs: 
      - setup_job
    
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello
        run: echo "Hello from build job"
      - name: Display the content on github github-action.txt
        run: cat github-action.txt



  deploy_job:
    needs: build_job
     
    runs-on: macos-latest
    steps:
      - name: Deploy step
        run: echo "Hello from deploy job"
