name: Demo2

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show system uptime
        run: uptime

      - name: Show current directory
        run: pwd

      - name: Display OS release information
        run: cat /etc/os-release

      - name: Show memory usage
        run: free -h
