name: Demo pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
  # schedule:
  #   - cron: "*/1 * * * *"     # Runs every minute

jobs:

  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create file
        run: touch github-action.txt

      - name: Print Hello world
        run: echo "Hello world"

      - name: Display README file
        run: cat README.md


  build_job:
    needs:
      - setup_job
      - deploy_job
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello
        run: echo "Hello from build job"


  deploy_job:
    needs: deploy_job  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Hello from deploy job"
